spring:
  application:
    name: dnd-characters-api
  datasource:
    url: jdbc:postgresql://localhost:5432/dnd_characters
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

dice:
  api-url: https://rolz.org/api/